version: '3.10'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566-4583:4566-4583
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      # - EDGE_PORT=4566
      - SERVICES=lambda,s3,ec2,eks,iam,ecr,rds
      - LOCALSTACK_API_KEY=*******
    volumes:
      - /srv/localstack_docker_data:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
